### ISSUE TITLE
image layout not set until after resizing the page

### ISSUE THREAD

**Issue by enjoylife** [neptunian/react-photo-gallery#1] opened 2015-12-16 18:48 UTC
On the demo GitHub page the layout doesn't properly tile itself until after I resize the page.

**Comment by neptunian** [comment] 2015-12-16 19:36
@enjoylife I'm not experiencing this.  Which browser/environment are you using?

**Comment by neptunian** [comment] 2015-12-16 19:43
@enjoylife  also what is the width of your viewport that you are experiencing this?  it might be some fluke width size that it fails at.  If that is the case, if you refresh at a different width, does it go away?

**Comment by enjoylife** [comment] 2015-12-17 01:29
Chrome, and it happens on any starting width.

![image](https://cloud.githubusercontent.com/assets/877194/11858897/94231240-a41a-11e5-955b-0cecbcc22375.png)

**Comment by neptunian** [comment] 2015-12-17 04:40
I can see this in my windows environment but not in others.  This seems to be caused by findDomNode clientWidth getting the incorrect width in certain environments and thereby creating images too large for the container width.  Will look further into it.

**Comment by neptunian** [comment] 2015-12-17 19:46
fixed in commit 0cafe9ab4374f49ac6c729496a22f6992c681bea

**Closed by neptunian** 2015-12-17 19:46 UTC
Labels: bug

**Comment by enjoylife** [comment] 2015-12-18 05:54
nice! Thanks for looking into it.
